import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
mkdirSync(resolve(root, 'apps/backend/dist'), { recursive: true });
writeFileSync(resolve(root, 'apps/backend/dist/server.js'), `import http from 'node:http';
const subjects=['Русский язык ОГЭ','Математика ОГЭ','Обществознание ОГЭ','Английский язык ОГЭ','Русский язык ЕГЭ','Математика ЕГЭ','Обществознание ЕГЭ','История ЕГЭ','Информатика ЕГЭ','Английский язык ЕГЭ'].map((title,i)=>({id:title.toLowerCase().replaceAll(' ','-'),title,examType:title.includes('ОГЭ')?'ОГЭ':'ЕГЭ',description:'Демонстрационный курс подготовки',topicCount:6,taskCount:18,progress:20+i*5}));
const topicNames=['Числа и вычисления','Алгебраические выражения','Уравнения','Неравенства','Функции','Геометрия','Вероятность и статистика','Текстовые задачи','Орфография','Пунктуация','Синтаксис','Изложение','Сочинение','Анализ текста','Экономика','Право','Политика','Лексика','Грамматика','Чтение'];
const topics=subjects.flatMap((s,si)=>topicNames.slice(0,si<2?8:4).map((title,i)=>({id:s.id+'-t'+(i+1),subjectId:s.id,title,description:'Тренировка темы '+title})));
const tasks=topics.flatMap((t,i)=>Array.from({length:3},(_,j)=>({id:'task-'+(i*3+j+1),topicId:t.id,question:'Демонстрационное задание по теме «'+t.title+'».',type:j===2?'TEXT':'MULTIPLE_CHOICE',options:j===2?[]:[{label:'A',text:'Типичная ошибка'},{label:'B',text:'Верный ответ'},{label:'C',text:'Неполный ответ'}],correctAnswer:j===2?'42':'B',explanation:'Подробное объяснение по теме «'+t.title+'».',difficulty:j+1})));
const sessions=[]; const results=[]; const user={id:'demo-user',name:'Демо Ученик',email:'demo@example.ru',role:'student'};
function json(res,code,data){res.writeHead(code,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'content-type, authorization','access-control-allow-methods':'GET,POST,PUT,OPTIONS'});res.end(JSON.stringify(data))}
async function body(req){let s=''; for await (const c of req) s+=c; try{return JSON.parse(s||'{}')}catch{return {}}}
function progress(){const correct=results.filter(r=>r.isCorrect).length; return {solvedTasks:results.length,correctAnswers:correct,mistakes:results.length-correct,progressPercent:Math.round(correct/Math.max(1,results.length)*100),weakTopics:['Пунктуация','Уравнения'],latestTests:sessions}}
http.createServer(async (req,res)=>{const url=new URL(req.url,'http://localhost'); if(req.method==='OPTIONS') return json(res,200,{}); if(url.pathname==='/health') return json(res,200,{ok:true}); if(url.pathname==='/auth/login'||url.pathname==='/auth/register') return json(res,200,{token:'demo-token',user}); if(url.pathname==='/me') return json(res,200,{user,progress:progress()}); if(url.pathname==='/subjects') return json(res,200,subjects); let m=url.pathname.match(new RegExp('^/subjects/([^/]+)$')); if(m) return json(res,200,subjects.find(s=>s.id===decodeURIComponent(m[1]))||subjects[0]); m=url.pathname.match(new RegExp('^/subjects/([^/]+)/topics$')); if(m) return json(res,200,topics.filter(t=>t.subjectId===decodeURIComponent(m[1]))); m=url.pathname.match(new RegExp('^/topics/([^/]+)/tasks$')); if(m) return json(res,200,tasks.filter(t=>t.topicId===decodeURIComponent(m[1])).map(({correctAnswer,...t})=>t)); m=url.pathname.match(new RegExp('^/tasks/([^/]+)$')); if(m&&req.method==='GET'){const task=tasks.find(t=>t.id===decodeURIComponent(m[1])); const {correctAnswer,...safe}=task||tasks[0]; return json(res,200,safe)} if(m&&req.method==='POST'){const b=await body(req); const task=tasks.find(t=>t.id===decodeURIComponent(m[1]))||tasks[0]; const isCorrect=String(b.answer||'').trim().toLowerCase()===task.correctAnswer.toLowerCase(); results.push({taskId:task.id,isCorrect}); return json(res,200,{isCorrect,correctAnswer:task.correctAnswer,explanation:task.explanation})} if(url.pathname==='/progress') return json(res,200,progress()); if(url.pathname.includes('/progress/subjects/')) return json(res,200,{progressPercent:42,solvedTasks:8,correctAnswers:5}); if(url.pathname==='/tests/start'){const b=await body(req); const selected=tasks.slice(0,Number(b.count||5)); const s={id:'test-'+Date.now(),userId:user.id,subjectId:b.subjectId,status:'IN_PROGRESS',totalTasks:selected.length,score:0,answers:[]}; sessions.push(s); return json(res,201,{...s,tasks:selected})} if(url.pathname.includes('/tests/')&&url.pathname.endsWith('/answer')) return json(res,200,{isCorrect:true}); if(url.pathname.includes('/tests/')&&url.pathname.endsWith('/finish')) return json(res,200,{score:4,percent:80,mistakes:[],weakTopics:['Уравнения'],recommendation:'Повторите слабые темы.'}); if(url.pathname==='/tests/history') return json(res,200,sessions); if(url.pathname.startsWith('/admin/')) return json(res,200,{ok:true,users:[user],subjects:subjects.length,topics:topics.length,tasks:tasks.length}); json(res,404,{message:'Not found'});}).listen(process.env.PORT||4000,()=>console.log('API запущен на http://localhost:'+(process.env.PORT||4000)));`);
console.log('backend build: apps/backend/dist/server.js');
