import { useEffect, useMemo, useState } from 'react';
import { BookOpen, ChartNoAxesCombined, CheckCircle2, GraduationCap, Moon, ShieldCheck, Sparkles, UserRound } from 'lucide-react';
import { currentUser, getProgress, getSubjects, getTasks, getTopics, login, logout, register, type User } from './lib/api';
import { subjects as mockSubjects, tasks as mockTasks, topics as mockTopics, type Subject, type Task, type Topic } from './lib/mockData';
import { recordAnswer, type DemoProgress } from './lib/storage';
import './styles.css';

type Page = 'home'|'subjects'|'topics'|'task'|'test'|'profile'|'admin';
const benefits = ['задания по темам','объяснения ошибок','личный прогресс','тренировочные тесты','слабые места'];
function ProgressBar({ value }: { value:number }) { return <div className="h-2 rounded-full bg-slate-200"><div className="h-2 rounded-full bg-blue-600" style={{width:`${Math.min(100,value)}%`}} /></div>; }
export default function App() {
  const [page,setPage] = useState<Page>('home'); const [user,setUser] = useState<User|null>(currentUser()); const [subjects,setSubjects] = useState<Subject[]>(mockSubjects); const [selectedSubject,setSelectedSubject] = useState<Subject>(mockSubjects[1]); const [topics,setTopics] = useState<Topic[]>([]); const [selectedTopic,setSelectedTopic] = useState<Topic|null>(null); const [task,setTask] = useState<Task>(mockTasks[0]); const [answer,setAnswer] = useState(''); const [result,setResult] = useState<string|null>(null); const [progress,setProgress] = useState<DemoProgress|null>(null); const [testCount,setTestCount] = useState(5); const [testAnswers,setTestAnswers] = useState<Record<string,string>>({});
  useEffect(()=>{ getSubjects().then(setSubjects); getProgress().then(setProgress); },[]);
  async function openSubject(subject:Subject){ setSelectedSubject(subject); const list = await getTopics(subject.id); setTopics(list); setPage('topics'); }
  async function openTopic(topic:Topic){ setSelectedTopic(topic); const list = await getTasks(topic.id); setTask(list[0] ?? mockTasks[0]); setAnswer(''); setResult(null); setPage('task'); }
  function checkTask(){ const ok = (answer || '').trim().toLowerCase() === (task.correctAnswer ?? 'B').toLowerCase(); setResult(ok ? 'Правильно! Отличная работа.' : 'Есть ошибка. Посмотри объяснение ниже.'); const topicName = selectedTopic?.title ?? mockTopics.find(t=>t.id===task.topicId)?.title ?? 'Тема'; setProgress(recordAnswer(ok, topicName)); }
  const testTasks = useMemo(()=>mockTasks.filter(t=>mockTopics.find(topic=>topic.id===t.topicId)?.subjectId===selectedSubject.id).slice(0,testCount),[selectedSubject,testCount]);
  const testScore = testTasks.filter(t => (testAnswers[t.id] || '').toLowerCase() === (t.correctAnswer ?? 'B').toLowerCase()).length;
  return <div className="min-h-screen bg-slate-50 text-ink"><header className="sticky top-0 z-10 border-b border-slate-200 bg-white/90 backdrop-blur"><nav className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3"><button onClick={()=>setPage('home')} className="flex items-center gap-2 font-bold"><GraduationCap className="text-blue-600"/> ОГЭ/ЕГЭ Помощник</button><div className="hidden gap-2 md:flex">{[['subjects','Предметы'],['test','Тест'],['profile','Кабинет'],['admin','Админка']].map(([p,t])=><button key={p} onClick={()=>setPage(p as Page)} className="nav">{t}</button>)}</div><div className="flex items-center gap-2">{user?<><span className="rounded-full bg-blue-50 px-3 py-1 text-sm text-blue-700">{user.name}</span><button className="btn ghost" onClick={()=>{logout();setUser(null)}}>Выйти</button></>:<button className="btn" onClick={()=>setPage('profile')}>Войти</button>}<Moon size={18}/></div></nav></header><main className="mx-auto max-w-7xl px-4 py-8">
  {page==='home' && <section className="grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl bg-gradient-to-br from-blue-700 to-indigo-700 p-8 text-white shadow-soft"><p className="mb-4 inline-flex rounded-full bg-white/15 px-3 py-1 text-sm"><Sparkles size={16}/> системная подготовка</p><h1 className="text-4xl font-bold md:text-6xl">Готовься к ОГЭ и ЕГЭ системно</h1><p className="mt-5 max-w-2xl text-lg text-blue-50">Выбирай предмет, решай задания, получай объяснения и отслеживай слабые темы без хаоса в подготовке.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={()=>setPage('subjects')} className="btn light">Начать подготовку</button><button onClick={()=>setPage('subjects')} className="btn outline">Выбрать предмет</button><button onClick={()=>setPage('test')} className="btn outline">Пройти тест</button></div></div><div className="grid gap-4">{benefits.map((b,i)=><div className="card flex items-center gap-3" key={b}><CheckCircle2 className="text-emerald-500"/><div><b>{b}</b><p className="text-sm text-slate-500">Шаг {i+1}: измеряем и улучшаем результат.</p></div></div>)}</div></section>}
  {page==='subjects' && <section><h2 className="title">Предметы</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{subjects.map(s=><article className="card" key={s.id}><div className="flex justify-between"><h3 className="text-xl font-bold">{s.title}</h3><span className="badge">{s.examType}</span></div><p className="mt-3 text-slate-600">{s.description}</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><span>{s.topicCount} тем</span><span>{s.taskCount} заданий</span></div><div className="my-4"><ProgressBar value={s.progress}/><p className="mt-1 text-sm text-slate-500">Прогресс {s.progress}%</p></div><button className="btn" onClick={()=>openSubject(s)}>Начать</button></article>)}</div></section>}
  {page==='topics' && <section><button className="link" onClick={()=>setPage('subjects')}>← к предметам</button><h2 className="title">{selectedSubject.title}: темы</h2><div className="grid gap-4 md:grid-cols-2">{topics.map(t=><button className="card text-left hover:border-blue-300" key={t.id} onClick={()=>openTopic(t)}><BookOpen className="text-blue-600"/><h3 className="mt-2 text-lg font-bold">{t.title}</h3><p className="text-slate-600">{t.description}</p></button>)}</div></section>}
  {page==='task' && <section className="mx-auto max-w-3xl"><button className="link" onClick={()=>setPage('topics')}>← к темам</button><div className="card"><div className="mb-4 flex gap-2"><span className="badge">{selectedTopic?.title}</span><span className="badge">сложность {task.difficulty}/3</span></div><h2 className="text-2xl font-bold">{task.question}</h2><div className="mt-5 space-y-2">{task.options.length?task.options.map(o=><label className="option" key={o.label}><input type="radio" name="answer" onChange={()=>setAnswer(o.label)}/> {o.label}. {o.text}</label>):<input className="input" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Введите ответ"/>}</div><button className="btn mt-5" onClick={checkTask}>Проверить</button>{result&&<div className="mt-5 rounded-2xl bg-blue-50 p-4"><b>{result}</b><p className="mt-2">{task.explanation}</p><button className="btn ghost mt-3" onClick={()=>{const idx=mockTasks.findIndex(t=>t.id===task.id);setTask(mockTasks[idx+1] ?? mockTasks[0]);setResult(null);setAnswer('')}}>Следующее задание</button></div>}</div></section>}
  {page==='test' && <section><h2 className="title">Тренировочный тест</h2><div className="card mb-5 flex flex-wrap gap-3"><select className="input" value={selectedSubject.id} onChange={e=>setSelectedSubject(subjects.find(s=>s.id===e.target.value) ?? subjects[0])}>{subjects.map(s=><option value={s.id} key={s.id}>{s.title}</option>)}</select>{[5,10,20].map(n=><button className="btn ghost" onClick={()=>setTestCount(n)} key={n}>{n} заданий</button>)}</div><div className="grid gap-4">{testTasks.map((t,i)=><div className="card" key={t.id}><b>{i+1}. {t.question}</b><input className="input mt-3" placeholder="Ответ: B или 42" onChange={e=>setTestAnswers({...testAnswers,[t.id]:e.target.value})}/></div>)}</div><div className="card mt-5"><h3 className="text-xl font-bold">Результат: {testScore}/{testTasks.length} ({Math.round(testScore/Math.max(1,testTasks.length)*100)}%)</h3><p>Слабые темы: {progress?.weakTopics.join(', ')}</p><p>Рекомендация: повторите темы с ошибками и решите ещё 5 заданий.</p></div></section>}
  {page==='profile' && <Profile user={user} setUser={setUser} progress={progress}/>} {page==='admin' && <Admin subjects={subjects}/>} </main></div>;
}
function Profile({user,setUser,progress}:{user:User|null;setUser:(u:User)=>void;progress:DemoProgress|null}){ const [mode,setMode]=useState<'login'|'register'>('login'); const [name,setName]=useState('Новый ученик'); const [email,setEmail]=useState('demo@example.ru'); const [password,setPassword]=useState('demo1234'); async function submit(){ const data = mode==='login'? await login(email,password): await register(name,email,password); setUser(data.user); } if(!user) return <section className="mx-auto max-w-lg card"><h2 className="title">Регистрация и вход</h2>{mode==='register'&&<input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Имя"/>}<input className="input" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Пароль"/><button className="btn mt-3" onClick={submit}>{mode==='login'?'Войти':'Зарегистрироваться'}</button><button className="link ml-3" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Создать аккаунт':'Уже есть аккаунт'}</button><p className="mt-4 text-sm text-slate-500">Если backend недоступен, включится demo-login через localStorage.</p></section>; return <section><h2 className="title">Личный кабинет</h2><div className="grid gap-4 md:grid-cols-4"><Stat icon={<UserRound/>} title="Ученик" value={user.name}/><Stat icon={<ChartNoAxesCombined/>} title="Прогресс" value={`${progress?.progressPercent ?? 0}%`}/><Stat icon={<CheckCircle2/>} title="Решено" value={`${progress?.solvedTasks ?? 0}`}/><Stat icon={<ShieldCheck/>} title="Верно" value={`${progress?.correctAnswers ?? 0}`}/></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="card"><h3 className="font-bold">Слабые темы</h3>{progress?.weakTopics.map(t=><span className="badge mr-2 mt-2" key={t}>{t}</span>)}</div><div className="card"><h3 className="font-bold">Последние тесты</h3>{progress?.latestTests.map((t:any)=><p key={t.id}>{t.subjectId}: {t.score}/{t.totalTasks}</p>)}</div></div></section> }
function Stat({icon,title,value}:{icon:React.ReactNode;title:string;value:string}){return <div className="card">{icon}<p className="text-sm text-slate-500">{title}</p><b className="text-2xl">{value}</b></div>}
function Admin({subjects}:{subjects:Subject[]}){return <section><h2 className="title">Админ-панель</h2><div className="grid gap-4 md:grid-cols-2"><div className="card"><h3 className="font-bold">Добавление контента</h3>{['Название предмета','Название темы','Текст задания','Правильный ответ'].map(p=><input className="input" placeholder={p} key={p}/>) }<button className="btn mt-3">Сохранить</button></div><div className="card"><h3 className="font-bold">Статистика</h3><p>Предметов: {subjects.length}</p><p>Пользователей: demo + admin</p><p>Разделы: добавление предметов, тем, заданий, редактирование заданий, просмотр пользователей.</p></div></div></section>}
